backtest_id: debug_data_test
strategy:
  class_path: backtesting.strategies.debug_strategy.DebugStrategy
  parameters:
    symbols:
      - GBPUSD

market_data:
  type: pipeline
  parameters:
    processed_data_path: data/storage/capital_com/processed/processed_GBPUSD_m5_20240101_20250101.csv
    symbols:
      - GBPUSD
    date_col: date

initial_capital: 10000.0
